name: Deploy Microservices Application

on:
  push:
    branches:
      - ec2  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Ensure this secret contains the correct private key

      - name: SSH into EC2 and Deploy
        run: |
          ssh -tt -o StrictHostKeyChecking=no ubuntu@ec2-65-0-131-78.ap-south-1.compute.amazonaws.com << 'EOF'
          # Define the project directory
          PROJECT_DIR="/home/ubuntu/my-project"  # Adjust this path to your project directory

          # Clone the repository if it doesn't exist, otherwise pull the latest changes
          if [ ! -d "$PROJECT_DIR" ]; then
            git clone https://github.com/IsuruVithanage/TradeX-Web-Backend.git $PROJECT_DIR
          else
            cd $PROJECT_DIR
            git pull
          fi

          cd $PROJECT_DIR  # Navigate to the project directory
          
          # Ensure Docker Compose is installed
          if ! command -v docker-compose &> /dev/null
          then
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Build and run the Docker containers
          docker-compose down
          docker-compose build
          docker-compose up -d
          EOF
