name: Deploy Microservices Application

on:
  push:
    branches:
      - ec2  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: SSH into EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-65-0-131-78.ap-south-1.compute.amazonaws.com << 'EOF'
          # Define the project directory
          PROJECT_DIR="/home/ubuntu/my-project"  # Adjust this path to your project directory

          # Clone the repository if it doesn't exist, otherwise pull the latest changes
          if [ ! -d "$PROJECT_DIR" ]; then
            git clone https://github.com/IsuruVithanage/TradeX-Web-Backend.git $PROJECT_DIR
          else
            cd $PROJECT_DIR
            git pull
          fi

          cd $PROJECT_DIR  # Navigate to the project directory
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose pull
          docker-compose down
          docker-compose up -d
          EOF